"""initial_schema

Revision ID: 1661390d6604
Revises: 
Create Date: 2026-06-01 11:16:06.857592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1661390d6604'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooksubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooksubscription_url'), 'webhooksubscription', ['url'], unique=False)
    op.drop_index(op.f('ix_attendee_email'), table_name='attendee')
    op.create_index(op.f('ix_attendee_email'), 'attendee', ['email'], unique=False)
    op.add_column('event', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('collect_company', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('duration_days', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('custom_fields_schema', sa.JSON(), nullable=True))
    op.add_column('event', sa.Column('allowed_domains', sa.JSON(), nullable=True))
    op.add_column('event', sa.Column('banner_settings', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'event', 'client', ['client_id'], ['id'])
    op.add_column('registration', sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('registration', sa.Column('custom_answers', sa.JSON(), nullable=True))
    op.add_column('registration', sa.Column('checked_in_days', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permissions')
    op.drop_column('registration', 'checked_in_days')
    op.drop_column('registration', 'custom_answers')
    op.drop_column('registration', 'pin')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'banner_settings')
    op.drop_column('event', 'allowed_domains')
    op.drop_column('event', 'custom_fields_schema')
    op.drop_column('event', 'duration_days')
    op.drop_column('event', 'collect_company')
    op.drop_column('event', 'client_id')
    op.drop_column('event', 'banner_url')
    op.drop_column('event', 'address')
    op.drop_index(op.f('ix_attendee_email'), table_name='attendee')
    op.create_index(op.f('ix_attendee_email'), 'attendee', ['email'], unique=1)
    op.drop_index(op.f('ix_webhooksubscription_url'), table_name='webhooksubscription')
    op.drop_table('webhooksubscription')
    # ### end Alembic commands ###
